module EventList exposing (..)

import Dict
import Types exposing (Event)


unitDict : Dict.Dict String (List Event)
unitDict =
    Dict.fromList
        [ ( "I"
          , [ Event "Founding of Jamestown" 1607 "First permanent British settlement in what would become the United States. Built on tabacco and trade with Native Americans, it had many more men than women—and an extremely high death rate in the early years."
            , Event "First slaves in British America" 1619 "Slavery did not become popular in Virginia until around 1660 because of the high death rate of residents...."
            , Event "The Mayflower arrives in Plimouth" 1620 "The \"Pilgrims\" of Plimouth were a slightly different form of protestantism than the Puritans of the Massachusetts Bay Colony; the two colonies were merged at the end of the 17th century. Though the Mayflower Company was intended to make money to repay its investors, it wasn't until the colony gave up its communal cultivation of land that it stopped being in danger of starving. (They would of course have starved without help from their Native American neighbors.)"
            , Event "Boston founded" 1630 "Named after Boston, England, Boston was the capital of the Massachusetts Bay Colony"
            , Event "Charles the First executed" 1649 "Charles the First walked and talked half an hour after his head was cut off."
            , Event "Hobbes' Leviathan Published" 1651 "Hobbes' work justified monarchy in the human attempt to escape the \"nasty, brutish, solitary, and short\" State of Warre"
            , Event "Restoration of the Monarchy in Britain" 1660 "After the \"Commonwealth Period\" when the British decided they didn't like Puritan rule under Oliver Cromwell, Charles II was restored to the throne."
            , Event "First slave law in Virginia" 1661 "This was the first of a series of laws that had the effect of closing off avenues to freedom and separating Black slaves and white indentured servants."
            , Event "King Phillip's War begins" 1675 "The bloodiest war in US History in terms of the percentage of residents killed as a \"Pan-Indian\" alliance under the Wampanoag leader Metacom pushed back against English settler encroachment"
            , Event "Dominion of New England created" 1686 "As part of the restored English monarchy's attempt to raise funds, Massachusetts, New York, and other colonies are merged into a mega-colony under the hated Sir Edmond Andros. After James II is deposed, the colonies revert to their earlier charters."
            , Event "Glorious Revolution of 1688" 1688 "After the Catholic James II had a son (replacing James' Protestant daughter Mary in the succession), he was deposed."
            , Event "Second Treatise on Civil Goverment" 1689 "Locke's seminal work justifying the Glorious Revolution of 1688 spelled out the right to revolution against a tyrannical goverment and promoted the (common!) idea that a person owned what they had created by their labor... unless someone else was paying for that labor."
            , Event "Salem Witch Hysteria" 1692 "There is no concensus as to what happened to turn the people of village of Danvers (not Salem) against their neighbors—was it ergot? the anxiety of Massachusetts' losing its status as a Puritan theocracy with most British control in the new 1691 charter? A land grab? Punishment against outspoken women? Undisputed: 19 were hanged, and six others lost their lives."
            ]
          )
        , ( "II"
          , [ Event "Navigation Acts" 1660 "The Navigation Acts restricted colonial trade and imposed various taxes as part of James II's attempt to raise funds."
            , Event "\"The Grumbling Hive\"" 1705 "This scandalous poem by Bernard Mandeville explored the idea that greed is good for the economy"
            , Event "Fort Necessity" 1754 "A young George Washington makes several poor tactical and diplomatic decisions in the Ohio River valley and, Horace Walpole said, \"set the world on fire.\""
            , Event "The Albany Plan of Union" 1754 "Benjamin Franklin propsed the first intercontinental government to protect the colonies from France; his famous \"Join or Die\" cartoon supported the failed proposal."
            , Event "Seven Year's War begins" 1756 "Seven Year's War begins"
            , Event "Peace of Paris" 1763 "The treaty ended the Seven Year's War, giving India and Canada to the British"
            , Event "Proclamation Line" 1763 "To avoid more frontier wars after Pontiac's \"pan-Indian\" rebellion, the British restricted settlement past the Appalachians."
            , Event "Sugar Tax" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British lowered the old Molasses tax but pledged to enforce it, trying smugglers in courts of admiralty."
            , Event "Currency Act" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British insisted all taxes from the colonies must be paid in gold or silver. Peter Cooper argued this was the cause of the Revolution."
            , Event "Stamp Act" 1765 "Though never enforced, this tax on paper and products made with paper caused widespread rioting across the colonies."
            , Event "Stamp Act Congress" 1765 "The Stamp Act Congress was the first successful intercolonial organization, bringing together nine of the colonies."
            , Event "Declaratory Act" 1766 "After repealing the Stamp Tax, Parliament asserted it still had the power to make legislation for the colonies."
            , Event "James Otis' speech against Writs of Assistance" 1761 "Otis' fiery speech against the warrantless searches illustrates the colonial belief that their freedoms came from the Magna Carta."
            , Event "Townshend Acts" 1767 "These taxes on middle class goods such as tea, paper, and glass spured the non-importation agreements and  Homespun Movement. Rioting in Boston brought troops to the city."
            , Event "Boston Massacre" 1770 "Paul Revere's engraving of the killing of five Bostonians by the British troops helped turn popular opinion against the British"
            , Event "Tea Act" 1773 "The Tea Act seems to fulfill the earlier warnings of John Dickinson that Parliament would \"complete\" the enslavement of the colonists by requiring them to import a good and then tax it."
            , Event "Tea Party" 1773 "In response to the Tea Act, an organized band in Boston destroyed the equivalent of four million dollars of tea."
            , Event "Intolerable Acts" 1774 "Called the \"Coercive Acts\" in Britain, these laws were in place until Massachusetts repaid what was destroyed in the Tea Party. The acts included closing Boston Harbor and dissolving the colonial government. The Québec Act was not part of the Coercive Acts, but it seemed part of the Catholic plot to enslave the colonists."
            , Event "Battle of Lexington and Concord" 1775 "On the 18th of April, in '75—hardly a man is now alive to remember that famous day and year.... Minutemen fanned across Middlesex county to warn the redcoats were planning to seize the colony's power and arrest the rebel leaders"
            , Event "Olive Branch Petition" 1775 "In the summer, the Continental Congress attempts to smooth things over with the King. (The Petition is ignored.)"
            , Event "Common Sense published" 1776 "Credited with addressing many loyalist concerns and using religious and Enlightenment imagry to rouse the population, Thomas Paine's tract was credited by many, including George Washington, with turning public opinion in favor of the Patriots."
            , Event "Wealth of Nations published" 1776 "Adam Smith's seminal work promoted the idea of an \"invisible hand in the market.\" Arguing that self-interest made an unregulated market self-regulation, Smith argued against older Mercantilist ideas."
            , Event "The Spirit of the Laws" 1748 "Montesquieu's book laid out the idea of checks and balances that would allow self-interest to prevent tyranny"
            , Event "The Declaration of Independence" 1776 "When in the Course of human events it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the Powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation."
            , Event "Treaty of Paris" 1783 "The Treaty of Paris ended the American Revolution, acknowledging that these United Colonies are, and of Right ought to be Free and Independent States... or at least, that they were now free and 13 separate entities."
            ]
          )
        , ( "VI"
          , [ Event "Mississippi Black Codes" 1865 "Mississippi and other states create laws to ensure continued labor supply and limit white/Black social contact."
            , Event "Civil Rights Act 1866 " 1866 "Much like the 14th amendment, the Civil Rights Act outlawed Black codes in the states. Vetoed by Johnson, then the veto overturned."
            , Event "Reconstruction Act" 1867 "Divided the former Confederate states into five military districts until they accepted the 14th amendment."
            , Event "14th Amendment  ratified" 1868 "Established equal protection under the law by race; birthright citizenship (and more)"
            , Event "Tenure of Office Act " 1868 "Law passed to require Johnson to get permission from Congress to fire members of his cabinet."
            , Event "Johnson Impeached" 1868 "After breaking the Tenure of Office Act, Johnson was impeached—but acquitted by one vote."
            , Event "Founding of the KKK" 1865 "The Ku Klux Klan is founded in response to reconstruction to maintain strict former racial hirearchies of slavery"
            , Event "15th Amendment ratified" 1870 "The US expands the franchize to Black men"
            , Event "Enforcement Acts" 1870 "Provide federal government authority for reconstruction"
            , Event "Colfax Massacre" 1873 "One of the most violent race riots in the South, led by the KKK"
            , Event "Slaughterhouse Cases" 1873 "This case dramatically limited the scope of the 14th amendment by saying it applied only to Federal laws."
            , Event "Whiskey Ring" 1875 "An example of the corruption of the Grant Administration"
            , Event "Molly Maguires Strike" 1875 "One of the most notorious strikes of the Gilded Age. "
            , Event "Paris Commune" 1871 "An short-lived worker's government in Paris that frightened those in the US."
            , Event "Cruikshank" 1876 "This case overturned the constitutionality of the Enforcement Acts."
            , Event "Great Railroad Strike" 1877 "Major strikes that had the effect of pulling troops out of the South."
            , Event "Bargain of 1877 " 1877 "Compromise after the contested election of 1876 that placed Hayes in the Presidency and sent troops back to their barracks in the south."
            , Event "Panic of 1873 " 1873 "Major economic depression that led many industrial workers unable to find full-time work."
            ]
          )
        , ( "III"
          , [ Event "First former colony outlaws slavery" 1777 "The Republic of Vermont outlaws slavery in its Constitution."
            , Event "Article of Confederation ratified" 1783 "The Articles created a \"firm league of friendship\" whose \"union\" would be \"perpetual.\""
            , Event "Treaty of Paris" 1783 "The Revolutionary War ends with a treaty between the King of England and 13 separate colonies."
            , Event "Quock Walker Case" 1783 "The Massachusetts Supreme Judifical Court decrees slavery inconsistent with the Commonwealth's constitution."
            , Event "Shays' Rebellion" 1786 "Tax revolt in Western Massachusetts that helps the push for a stronger central government."
            , Event "Northwest Ordinance" 1787 "Policy passed under the Articles that the land north of the Ohio and east of the Mississippi could become states, with slavery banned, and the rights to Native Americans respected (in theory)."
            , Event "Constitutional Convention" 1787 "Held in Philadelphia, the Constitutional Convention propsed a, well, Constitution."
            , Event "Constitutional ratified" 1788 "Helped by the Federalist Papers, New York and Virginia finally ratitied the Constitution, putting it into effect."
            , Event "The French Revolution" 1789 "At first, Americans of all parties were thrilled by the French Revolution."
            , Event "Dinner Table Bargin" 1790 "Alexander Hamilton agrees the capital should move to DC in exchange for Jefferson and Madison's support of his debt assumption plan."
            , Event "Bill of Rights Ratified" 1791 "Bill of Rights Ratified"
            , Event "Haitian Revolution begins" 1791 "Hamilton helps write the Constitution... but many slaveholders are terrified."
            , Event "Jay's Treaty" 1794 "Washington supports a treaty allying the US more closely with monarchical UK than with Republican France."
            , Event "Ugly Election of 1796" 1796 "Ugly fights between Federalist John Adams and Republican Thomas Jefferson. (Adams wins.)"
            , Event "XYZ Affair" 1798 "I don't care if you know about the XYZ Affair!"
            , Event "Alien and Sedition Acts" 1798 "The Alien act gave Congress new powers to expel (French) aliens; the Sedition Act violated the 1st amendment by making it a crime to criticize the government."
            , Event "Kentucky Resolution" 1798 "Written in response to the Sedition Act, Jefferson anonymously laid out the argument that states could \"nullify\" unconstitutional laws."
            , Event "Fries Rebellion" 1799 "Another Tax Revolt!"
            , Event "Revolution of 1800" 1800 "After another ugly election, the Federalists allow the winning Republicans to take office!"
            , Event "Whiskey Rebellion" 1794 "Washington leads the troops against rebelling farmers."
            , Event "Cotton Gin Patented" 1794 "Eli Whitney patents the machine that makes the growing of cotton highly profitable."
            ]
          )
        , ( "VII"
          , [ Event "Haymarket" 1886 "A labor protest that involved a bomb (with police violence in return) that frightened many that labor was growing threatening."
            , Event "Pullman Strike" 1894 "The strike that prompted Eugene V. Debs to propose a \"sympathy\" strike; Gompers refused; Debs was arrested."
            , Event "Homestead Strike" 1892 "A strike at Carnegie's plant where his righthand man, Henry Frick, called out the Pinkertons"
            , Event "Knights of Labor Founded" 1869 "An Industrial Union; the Knights of Labor largely collapsed as they did not respond quickly enough to Haymarker."
            , Event "AFL founded" 1886 "Run by Samuel Gompers more or less until 1924, this trades union often stood as the \"safer\" union movement."
            , Event "Munn v. IL" 1876 "One of the \"Granger\" case The Supreme Court found private property could be regulated if it was in the public interest."
            , Event "Wabash v. Ohio" 1886 "Wabash refined Munn v. IL, saying only the Federal Government could regulate railroads (under the interstate commerce clause)."
            , Event "Interstate Commerce Act" 1887 "Using the power granted in Wabash, Congress passed a law making the Interstate Commerce Commission, which could (but didn't much) regulate railroads. Is it still the Gilded Age?"
            , Event "Sherman Anti-Trust Act" 1890 "Anti-monopoly law that Sherman himself said was to avoid concentrated wealthy and power, which would be \"a kingly perogative... inconsistant with our form of government.\""
            , Event "Populist Platform" 1892 "The Populists demanded by more government regulation of monopolies and \"good government\" reforms to lessen the power of monopolies and other elites."
            , Event "Cross of Gold Speech" 1896 "William Jenning Bryan's pro-farmer (and slightly pro-silver) speech made him the darling of the Populists, who named the Democrat as their candidate; they were essentially absorbed back into the Democratic party after."
            , Event "Minor v . Happersett" 1876 "Virginia Minor was found to be a citizen... but not to have the right to vote."
            , Event "\"The Yellow Wallpaper\"" 1892 "Charlotte Perkins Gilman's famous story...."
            , Event "Hull House founded" 1889 "One of many Settlement Houses that allowed middle-class women (and some men) a way to serve the poor by living in poor neighborhoods."
            , Event "The Gospel of Wealth" 1889 "Andrew Carnegie's famous essay."
            , Event "Chicago World's Fair/Columbian Exposition" 1893 "The \"White City\" celebrates progress."
            , Event "Atlanta Compromise Speech" 1895 "Booker T. Washington urges his Black and white audience to \"cast down your bucket where you are.\""
            , Event "United States v. Wong Kim Ark" 1898 "Supreme Court case that the birthright citizenship promised by the 14th amendment applies to the children of Chinese immigrants born in the US."
            , Event "Plessy v. Ferguson" 1896 "Infamous case establishing that \"separate but equal\" accommodations were consistent with the 14th amendment."
            , Event "Williams v. Mississippi" 1898 "Case established that rules to present African-Americans from voting were Constitutional if they were not explicitly about race."
            ]
          )
        ]
