module EventList exposing (..)

import Dict
import Types exposing (Event)


unitDict : Dict.Dict String (List Event)
unitDict =
    Dict.fromList
        [ ( "I"
          , [ Event "Founding of Jamestown" 1607 "First permanent British settlement in what would become the United States. Built on tabacco and trade with Native Americans, it had many more men than women—and an extremely high death rate in the early years."
            , Event "First slaves in British America" 1619 "Slavery did not become popular in Virginia until around 1660 because of the high death rate of residents...."
            , Event "The Mayflower arrives in Plimouth" 1620 "The \"Pilgrims\" of Plimouth were a slightly different form of protestantism than the Puritans of the Massachusetts Bay Colony; the two colonies were merged at the end of the 17th century. Though the Mayflower Company was intended to make money to repay its investors, it wasn't until the colony gave up its communal cultivation of land that it stopped being in danger of starving. (They would of course have starved without help from their Native American neighbors.)"
            , Event "Boston founded" 1630 "Named after Boston, England, Boston was the capital of the Massachusetts Bay Colony"
            , Event "Charles the First executed" 1649 "Charles the First walked and talked half an hour after his head was cut off."
            , Event "Hobbes' Leviathan Published" 1651 "Hobbes' work justified monarchy in the human attempt to escape the \"nasty, brutish, solitary, and short\" State of Warre"
            , Event "Restoration of the Monarchy in Britain" 1660 "After the \"Commonwealth Period\" when the British decided they didn't like Puritan rule under Oliver Cromwell, Charles II was restored to the throne."
            , Event "First slave law in Virginia" 1661 "This was the first of a series of laws that had the effect of closing off avenues to freedom and separating Black slaves and white indentured servants."
            , Event "King Phillip's War begins" 1675 "The bloodiest war in US History in terms of the percentage of residents killed as a \"Pan-Indian\" alliance under the Wampanoag leader Metacom pushed back against English settler encroachment"
            , Event "Dominion of New England created" 1686 "As part of the restored English monarchy's attempt to raise funds, Massachusetts, New York, and other colonies are merged into a mega-colony under the hated Sir Edmond Andros. After James II is deposed, the colonies revert to their earlier charters."
            , Event "Glorious Revolution of 1688" 1688 "After the Catholic James II had a son (replacing James' Protestant daughter Mary in the succession), he was deposed."
            , Event "Second Treatise on Civil Goverment" 1689 "Locke's seminal work justifying the Glorious Revolution of 1688 spelled out the right to revolution against a tyrannical goverment and promoted the (common!) idea that a person owned what they had created by their labor... unless someone else was paying for that labor."
            , Event "Salem Witch Hysteria" 1692 "There is no concensus as to what happened to turn the people of village of Danvers (not Salem) against their neighbors—was it ergot? the anxiety of Massachusetts' losing its status as a Puritan theocracy with most British control in the new 1691 charter? A land grab? Punishment against outspoken women? Undisputed: 19 were hanged, and six others lost their lives."
            ]
          )
        , ( "II"
          , [ Event "Navigation Acts" 1660 "The Navigation Acts restricted colonial trade and imposed various taxes as part of James II's attempt to raise funds."
            , Event "\"The Grumbling Hive\"" 1705 "This scandalous poem by Bernard Mandeville explored the idea that greed is good for the economy"
            , Event "Fort Necessity" 1754 "A young George Washington makes several poor tactical and diplomatic decisions in the Ohio River valley and, Horace Walpole said, \"set the world on fire.\""
            , Event "The Albany Plan of Union" 1754 "Benjamin Franklin propsed the first intercontinental government to protect the colonies from France; his famous \"Join or Die\" cartoon supported the failed proposal."
            , Event "Seven Year's War begins" 1756 "Seven Year's War begins"
            , Event "Peace of Paris" 1763 "The treaty ended the Seven Year's War, giving India and Canada to the British"
            , Event "Proclamation Line" 1763 "To avoid more frontier wars after Pontiac's \"pan-Indian\" rebellion, the British restricted settlement past the Appalachians."
            , Event "Sugar Tax" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British lowered the old Molasses tax but pledged to enforce it, trying smugglers in courts of admiralty."
            , Event "Currency Act" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British insisted all taxes from the colonies must be paid in gold or silver. Peter Cooper argued this was the cause of the Revolution."
            , Event "Stamp Act" 1765 "Though never enforced, this tax on paper and products made with paper caused widespread rioting across the colonies."
            , Event "Stamp Act Congress" 1765 "The Stamp Act Congress was the first successful intercolonial organization, bringing together nine of the colonies."
            , Event "Declaratory Act" 1766 "After repealing the Stamp Tax, Parliament asserted it still had the power to make legislation for the colonies."
            , Event "James Otis' speech against Writs of Assistance" 1761 "Otis' fiery speech against the warrantless searches illustrates the colonial belief that their freedoms came from the Magna Carta."
            , Event "Townshend Acts" 1767 "These taxes on middle class goods such as tea, paper, and glass spured the non-importation agreements and  Homespun Movement. Rioting in Boston brought troops to the city."
            , Event "Boston Massacre" 1770 "Paul Revere's engraving of the killing of five Bostonians by the British troops helped turn popular opinion against the British"
            , Event "Tea Act" 1773 "The Tea Act seems to fulfill the earlier warnings of John Dickinson that Parliament would \"complete\" the enslavement of the colonists by requiring them to import a good and then tax it."
            , Event "Tea Party" 1773 "In response to the Tea Act, an organized band in Boston destroyed the equivalent of four million dollars of tea."
            , Event "Intolerable Acts" 1774 "Called the \"Coercive Acts\" in Britain, these laws were in place until Massachusetts repaid what was destroyed in the Tea Party. The acts included closing Boston Harbor and dissolving the colonial government. The Québec Act was not part of the Coercive Acts, but it seemed part of the Catholic plot to enslave the colonists."
            , Event "Battle of Lexington and Concord" 1775 "On the 18th of April, in '75—hardly a man is now alive to remember that famous day and year.... Minutemen fanned across Middlesex county to warn the redcoats were planning to seize the colony's power and arrest the rebel leaders"
            , Event "Olive Branch Petition" 1775 "In the summer, the Continental Congress attempts to smooth things over with the King. (The Petition is ignored.)"
            , Event "Common Sense published" 1776 "Credited with addressing many loyalist concerns and using religious and Enlightenment imagry to rouse the population, Thomas Paine's tract was credited by many, including George Washington, with turning public opinion in favor of the Patriots."
            , Event "Wealth of Nations published" 1776 "Adam Smith's seminal work promoted the idea of an \"invisible hand in the market.\" Arguing that self-interest made an unregulated market self-regulation, Smith argued against older Mercantilist ideas."
            , Event "The Spirit of the Laws" 1748 "Montesquieu's book laid out the idea of checks and balances that would allow self-interest to prevent tyranny"
            , Event "The Declaration of Independence" 1776 "When in the Course of human events it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the Powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation."
            , Event "Treaty of Paris" 1783 "The Treaty of Paris ended the American Revolution, acknowledging that these United Colonies are, and of Right ought to be Free and Independent States... or at least, that they were now free and 13 separate entities."
            ]
          )
        , ( "VI"
          , [ Event "Mississippi Black Codes" 1865 "Mississippi and other states create laws to ensure continued labor supply and limit white/Black social contact."
            , Event "Civil Rights Act 1866 " 1866 "Much like the 14th amendment, the Civil Rights Act outlawed Black codes in the states. Vetoed by Johnson, then the veto overturned."
            , Event "Reconstruction Act" 1867 "Divided the former Confederate states into five military districts until they accepted the 14th amendment."
            , Event "14th Amendment  ratified" 1868 "Established equal protection under the law by race; birthright citizenship (and more)"
            , Event "Tenure of Office Act " 1868 "Law passed to require Johnson to get permission from Congress to fire members of his cabinet."
            , Event "Johnson Impeached" 1868 "After breaking the Tenure of Office Act, Johnson was impeached—but acquitted by one vote."
            , Event "Founding of the KKK" 1865 "The Ku Klux Klan is founded in response to reconstruction to maintain strict former racial hirearchies of slavery"
            , Event "15th Amendment ratified" 1870 "The US expands the franchize to Black men"
            , Event "Enforcement Acts" 1870 "Provide federal government authority for reconstruction"
            , Event "Colfax Massacre" 1873 "One of the most violent race riots in the South, led by the KKK"
            , Event "Slaughterhouse Cases" 1873 "This case dramatically limited the scope of the 14th amendment by saying it applied only to Federal laws."
            , Event "Whiskey Ring" 1875 "An example of the corruption of the Grant Administration"
            , Event "Molly Maguires Strike" 1875 "One of the most notorious strikes of the Gilded Age. "
            , Event "Paris Commune" 1871 "An short-lived worker's government in Paris that frightened those in the US."
            , Event "Cruikshank" 1876 "This case overturned the constitutionality of the Enforcement Acts."
            , Event "Great Railroad Strike" 1877 "Major strikes that had the effect of pulling troops out of the South."
            , Event "Bargain of 1877 " 1877 "Compromise after the contested election of 1876 that placed Hayes in the Presidency and sent troops back to their barracks in the south."
            , Event "Panic of 1873 " 1873 "Major economic depression that led many industrial workers unable to find full-time work."
            ]
          )
        , ( "VIII"
          , [Event "Hawaii becomes a territory" 1898 "Hawaii becomes a territory."
            , Event "Pledge of Allegiance written" 1892 "Pledge of Allegiance written by Francis Bellamy."
            , Event "Spanish-American War" 1898 "Remember the Maine!"
            , Event "Roosevelt Corollary" 1905 "It is not true that the United States feels any land hunger or entertains any projects as regards the other nations of the Western Hemisphere save such as are for their welfare. All that this country desires is to see the neighboring countries stable, orderly, and prosperous. Any country whose people conduct themselves well can count upon our hearty friendship. If a nation shows that it knows how to act with reasonable efficiency and decency in social and political matters, if it keeps order and pays its obligations, it need fear no interference from the United States. Chronic wrongdoing, or an impotence which results in a general loosening of the ties of civilized society, may in America, as elsewhere, ultimately require intervention by some civilized nation, and in the Western Hemisphere the adherence of the United States to the Monroe Doctrine may force the United States, however reluctantly, in flagrant cases of such wrongdoing or impotence, to the exercise of an international police power." 
            , Event "The Significance of the Frontier on American Life" 1890 "Frederick Jackson Turner's speech on how the frontier has brought continous democratic vitality to the United States (but that era has ended)." 
            , Event "Atlanta Compromise Speech" 1895 "Urging African-Americans to \"cast down their buckets where they are\" Booker T. Washington  pushed for economic equality while accepting that in social issues the races could be as separate as the fingers of the hand." 
            , Event "Niagara Movement" 1905 "Precursor of the founding of the NAACP, the Niagara Movement argued that social equality must happen at the same time as economic equality"
            ]
          )
        , ( "IX"
          , [ Event "Principals of Scientific Management" 1911 "Frederick Winslow Taylor's \"Taylorist\" manifesto on how to bring efficiency to industrial (and government) systems."
            , Event "Buck v Bell" 1925 "Court case that affirmed involutary sterilization (somewhat overturned by SKINNER v. OKLAHOMA in the 1940s)."
            , Event "Pure Food and Drug Act" 1906 "Congress took action on misleading advertisements and questionable ingredients in comestibles. Not CAUSED by THE JUNGLE though often people say it was."
            , Event "Hepburn Act" 1908 "Let's finally use Congress' power to regulate the railroads!"
            , Event "Clayton Act" 1914 "Let's protect unions while doing some trust-busting!"
            , Event "Owens Keating Act" 1916 "Overturned by the Supreme Court in 1918, this law limited child labor."
            , Event "16th Amendment" 1913 "An income tax!"
            , Event "17th Amendment" 1913 "Direct election of senators!"
            , Event "18th Amendment" 1918 "Allows Congress to regulate the sale of alcohol (they did so in the Volstead Act)"
            , Event "19th Amendment" 1920" 144 years (gross!) after the Declaration of Independence, women can vote! (30 countries did it first, after New Zealand set the trend in 1893. Maybe WYOMING  was the first vote-granting gov't to do it, in 1889?)"
            , Event "Sinking of Luisitania" 1915 "This British ship, carrying Americans (and arms) was a rallying cry for the US to enter the wa"
            , Event "WWI breaks out" 1914 "Out breaks World War I"
            , Event "Zimmerman Telegram" 1917 "US discovers Germany allying with Mexico"
            , Event "US joins WWI" 1917 "Wilson asks Congress for a declaration of war to make the world safe for Democracy..."
            , Event "WWI ends" 1918 "Treaty of Versailles signed in 1919... but not by US"
            , Event "Espinoage Act" 1917 "The Espinoage Act gave gov't power to control what was sent through the mail/ "
            , Event "Sedition Act" 1918 "The Sedition Act (the second after the one in 1898) allowed for the proscecution of those who advocated action against the US"
            , Event "Treaty of Versailles" 1919 "Created the League of Nations and put massive reparations on Germany"
            , Event "Johnson-Reed Act" 1924 "Closes most immigration to the United States"
            , Event "Birth of a Nation" 1915 "DW Griffith's epic depiction of the KKK restoring Southern (and Southern white women's) perceived honor---reinvigorates "
            , Event "Founding of the NAACP" 1909 "NAACP founded by mixed-race group"
            ]
          )
        , ( "III"
          , [ Event "First former colony outlaws slavery" 1777 "The Republic of Vermont outlaws slavery in its Constitution."
            , Event "Article of Confederation ratified" 1783 "The Articles created a \"firm league of friendship\" whose \"union\" would be \"perpetual.\""
            , Event "Treaty of Paris" 1783 "The Revolutionary War ends with a treaty between the King of England and 13 separate colonies."
            , Event "Quock Walker Case" 1783 "The Massachusetts Supreme Judifical Court decrees slavery inconsistent with the Commonwealth's constitution."
            , Event "Shays' Rebellion" 1786 "Tax revolt in Western Massachusetts that helps the push for a stronger central government."
            , Event "Northwest Ordinance" 1787 "Policy passed under the Articles that the land north of the Ohio and east of the Mississippi could become states, with slavery banned, and the rights to Native Americans respected (in theory)."
            , Event "Constitutional Convention" 1787 "Held in Philadelphia, the Constitutional Convention propsed a, well, Constitution."
            , Event "Constitutional ratified" 1788 "Helped by the Federalist Papers, New York and Virginia finally ratitied the Constitution, putting it into effect."
            , Event "The French Revolution" 1789 "At first, Americans of all parties were thrilled by the French Revolution."
            , Event "Dinner Table Bargin" 1790 "Alexander Hamilton agrees the capital should move to DC in exchange for Jefferson and Madison's support of his debt assumption plan."
            , Event "Bill of Rights Ratified" 1791 "Bill of Rights Ratified"
            , Event "Haitian Revolution begins" 1791 "Hamilton helps write the Constitution... but many slaveholders are terrified."
            , Event "Jay's Treaty" 1794 "Washington supports a treaty allying the US more closely with monarchical UK than with Republican France."
            , Event "Ugly Election of 1796" 1796 "Ugly fights between Federalist John Adams and Republican Thomas Jefferson. (Adams wins.)"
            , Event "XYZ Affair" 1798 "I don't care if you know about the XYZ Affair!"
            , Event "Alien and Sedition Acts" 1798 "The Alien act gave Congress new powers to expel (French) aliens; the Sedition Act violated the 1st amendment by making it a crime to criticize the government."
            , Event "Kentucky Resolution" 1798 "Written in response to the Sedition Act, Jefferson anonymously laid out the argument that states could \"nullify\" unconstitutional laws."
            , Event "Fries Rebellion" 1799 "Another Tax Revolt!"
            , Event "Revolution of 1800" 1800 "After another ugly election, the Federalists allow the winning Republicans to take office!"
            , Event "Whiskey Rebellion" 1794 "Washington leads the troops against rebelling farmers."
            , Event "Cotton Gin Patented" 1794 "Eli Whitney patents the machine that makes the growing of cotton highly profitable."
            ]
          )
        , ( "IV"
          , [Event "Revolution of 1800" 1800 "First peaceful transfer of power from one part to another as Federalists accept Democratic-Republican win."
            , Event "Louisiana Purchase" 1803 "US doubles in size. Federalists angry that the US is paying money (which it doesn't have) for land (which it does)"
            , Event "Marybury v. Madison" 1803 "Supreme Court announces it has the power of judicial review."
            , Event "The Duel" 1804 "Burr kills Hamilton—but use this to remember that there was a Federalist plot to secede."
            , Event "Embargo Act" 1807 "To avoid getting entangled in European wars, Congress limits trade with Europe, infuriating New England Federalists."
            , Event "Battle of Tippecanoe" 1811 "Worried about Tecumseh's pan-Indian alliance (which they think is supported by the British), the US army attacks his Prophetstown. "
            , Event "First Limited Liability Corporation" 1811 " New York introduces a powerful tool for capitalism: limiting liability so that shareholders were not responsibile for company losses...."
            , Event "First steamship on the Mississippi" 1811 "The first steamship.... was on the Mississippi"
            , Event "War of 1812 starts" 1812 "The war continues until 1815"
            , Event "Hartford Convention" 1815 "New England states want to limit Congresses power so they cannot be outvoted. Maybe threaten secession...?"
            , Event "Treaty of Ghent" 1815 "Ends the 1812 War"
            , Event "American System" 1816 "Congress proposes: A tariff, Bank, Canals and roads (Madison vetoes the last part)"
            , Event "Panic of 1819" 1819 "AAAAAAAHHHHHHHHH"
            , Event " McCullouch v. Maryland" 1819 "John Marshall makes the elastic clause very stretchy (\"be the ends legitimate... be it within the scope of the constitution\")"
            , Event "Missouri Compromise" 1820 "Missouri (slave) and Maine (free) enter as states, with the rest of the Louisiana Purchase Land divided at a line at the bottom of Missouri between slave and free."
            , Event "Erie Canal finished" 1825 "They finished a canal from Albany to Buffalo!"
            , Event "First Railroad in the US" 1828 "Go South Carolina!"
            , Event "Tariff of Abominations" 1828 "Otherwise known as the Tariff of 1828, this tariff was opposed by John C. Calhoun as detrimental to the South"
            , Event "Indian Removal Act" 1830 "Congress allows for \"voluntary\" moving of Native American Tribes past the Mississippi"
            , Event "Book of Mormon published" 1830 "Joseph Smith publishes the translation of the Golden Tablets given to him by the angel Moroni."
            , Event "Hayne-Webster Debate" 1830 "Daniel Webster holds forth for hours (days?) on why South Carolina is wrong to oppose taxes paying for improvements in other tates"
            , Event "Nat Turner Rebellion" 1831 "After receiving a vision that he should rise up against those oppressing him and other slaves, Nat Turner leads a rebellion that kills scores of white people in Virginia."
            , Event "Nullification Crisis" 1832 "South Carolina decides to nullify the Tariff of Abominations"
            , Event "Panic of 1837" 1837 "AAAHHHHH. I think, in a way, it causes the Civil War because it made it harder for states to fund infrastructure, leading to a breakdown in Van Buren's anti-sectional second party system..."
            , Event "Trail of Tears" 1838 "Like many other tribes, the Cherokee are involuntarily forced off their land by the US Government"
            , Event "Log Cabin Campaign" 1840 "William Henry Harrison runs as a common man (born in a log cabin he built with his own hands... joke!)"
            ]
          )
        , ( "V"
          , [Event "Rivers and Harbors Act" 1846 "A federal infrastructure bill vetoed by Polk that angered western Democrats, sending many to the Free Soil Party."
            , Event "Founding of the Free Soil Party" 1848 "An all-Northern political party made of Northern Democrats who favored westward expansion and \"internal improvements\" and anti-slavery \"conscience Whigs.\" Ironically, Van Buren was their candidate. (\"The Van Buren of Today,\" Charles Sumner called it.)"
            , Event "Gold Rush" 1849 "Ooops, now California needs a territorian government. Will it have slavery?"
            , Event "Compromise of 1850" 1850 "1) Free State (California) 8) [the 'ated] Fugitive Slave Act , Popular 5)overeignty in the Mexican Cession, 0 slave trade in DC"
            , Event "Uncle Tom's Cabin published" 1851 "Written in response to the Fugitive Slave Act, this block-buster novel made it harder for Northerners to ignore the miseries of slavery."
            , Event "Kansas-Nebraska Act" 1854 "Stephen Douglas (IL-D) proposed that the question of slavery in Kansas and Nebraska should be decided by popular sovereignty (thus changing the Missouri Compromise)."
            , Event "Ostend Manifesto" 1856 "Secret US document to European powers asserting the right to take Cuba."
            , Event "Filibusting of William Walker" 1856 "William Walker set up himself as President of Nicaragua. His \"filibusting\" came to be seen as pro-slavery."
            , Event "Dred Scott Case" 1857 "Roger Taney's court determined people of African descent were not citizens of the US and \"had no rights a white man was bound to respect''—and that Congress had no right  to make laws about slavery in the territories."
            , Event "Raid on Harper's Ferry" 1859 "Following his massacre of 5 pro-slavery men in Kansas, John Brown attempted to jump-start the Civil War by taking over a Virginia (now West Virginia) arsenal. That he was saluted by many prominent northerners was seen as a deep insult to the south."
            , Event "Lincoln-Douglas Debates" 1858 "In their battle for the senate two years before their presidential contest, Stephen Douglas and Abraham Lincoln met in 3-hour discussions that frequently focused on slavery though their home state (Illinois) was a free state."
            , Event "Election of Lincoln" 1860 "Lincoln won the 1860 election without a single electoral vote from the South."
            , Event "South Carolina secedes" 1861 "Following Lincoln's election, South Carolina announced the compact between itself and its sister states had already been broken by the actions of the North."
            , Event "Formation of the American or \"Know-Nothing\" party" 1844 "In 1855, this party changed its name from \"The Native American party.\" Commonly known as the \"Know-Nothings,\" it was a nativist, anti-immigrant party that swept Massachusetts elections in the 1850s."
            , Event "Formation of the Republican Party" 1856 "After the Whig party fell apart in response to Bleeding Kansas, Northern (but not southern) Whigs largerly moved to the new Republican Party."
            , Event "Formation of the Confederate States of America" 1861 "In February, seven states formed the CSA with a capital in Montgomery, AL before later moving to Richmond, Virginia. Others joined in March and April including parts of MO and KY."
            , Event "Battle of Manassas" 1861 "First major battle of the Civil War, a Confederate victory, also called the Battle of Bull Run. The extensive causalities signaled a new kind of war."
            , Event "Second Confiscation Act" 1862 "\"Congress anticipated Lincoln by passing a law allowing escaped confederate slaves to be considered free; to arm Black men... and to move towards \"colonization.\""
            , Event "New York Draft Riots" 1863 "Violent, often anti-African-American riots in New York City."
            , Event "Battle of Antietem" 1862 "Single most violent day in US History, with nearly 4,000 deaths on September 17 (Constitution Day). Though there was no clear victory,  Lincoln used it the pretext to issue the Preliminary Emancipation Proclamation."
            , Event "Preliminary Emancipation Proclamation" 1862 "On September 22, Lincoln gave the CSA until January 1st to rejoin the union or have their slaves freed by fiat."
            , Event "Emancipation Proclamation" 1863 "On January 1st, Lincoln proclaimed all slaves in the CSA free."
            , Event "Battle of Gettsyburg/Vicksburg" 1863 "These twin summer Union victories after brutal campaigns signaled a turning-point in the war."
            , Event "Gettysburg Address" 1863 "Four score and seven years after the Declaration of Independence, Lincoln issued this brief address."
            , Event "Sherman's \"March to the Sea\"" 1864 "William Tecumseh Sherman's destructive march across Georgia burned Atlanta and Savannah and signaled imminent Norther"
            , Event "Surrender at Appomattox" 1865 "On April 9th. Robert E. Lee surrendered to US Grant in a town called Appomattox Courthouse. "
            , Event "Lincoln Assassinated" 1865 "Lincoln was shot on April 14th and died a day later. "
            , Event "Invention of the Saxophone" 1846 "Saxophone invented"
            , Event "Liberty Party changes the election" 1844 "Henry Clay would have won the election if he had carried New York, but the Liberty Party took enough votes to change the outcome (if they'd vote for Clay)."
            , Event "Senate tips to the Free states" 1850 "With the addition of California,the House, Senate, and Electorial college were dominated by free states."
            , Event "Caning of Charles Sumner" 1856 "In response to Sumner's speech refering to the pro-slavery violence in Kansas as representing the \"spew and vomit of an uneasy civilization,\" Congressman Preston Brooks (SC) beat Sumner into a bloody pulp."
            , Event "\"House Divided Speech\"" 1858 "In his run for the Senate, Lincoln declared a conpiracy to spread slavery and said the country could not last half slave and half free."
            ]
          )
        , ( "VII"
          , [ Event "Haymarket" 1886 "A labor protest that involved a bomb (with police violence in return) that frightened many that labor was growing threatening."
            , Event "Pullman Strike" 1894 "The strike that prompted Eugene V. Debs to propose a \"sympathy\" strike; Gompers refused; Debs was arrested."
            , Event "Homestead Strike" 1892 "A strike at Carnegie's plant where his righthand man, Henry Frick, called out the Pinkertons"
            , Event "Knights of Labor Founded" 1869 "An Industrial Union; the Knights of Labor largely collapsed as they did not respond quickly enough to Haymarker."
            , Event "AFL founded" 1886 "Run by Samuel Gompers more or less until 1924, this trades union often stood as the \"safer\" union movement."
            , Event "Munn v. IL" 1876 "One of the \"Granger\" case The Supreme Court found private property could be regulated if it was in the public interest."
            , Event "Wabash v. Ohio" 1886 "Wabash refined Munn v. IL, saying only the Federal Government could regulate railroads (under the interstate commerce clause)."
            , Event "Interstate Commerce Act" 1887 "Using the power granted in Wabash, Congress passed a law making the Interstate Commerce Commission, which could (but didn't much) regulate railroads. Is it still the Gilded Age?"
            , Event "Sherman Anti-Trust Act" 1890 "Anti-monopoly law that Sherman himself said was to avoid concentrated wealthy and power, which would be \"a kingly perogative... inconsistant with our form of government.\""
            , Event "Populist Platform" 1892 "The Populists demanded by more government regulation of monopolies and \"good government\" reforms to lessen the power of monopolies and other elites."
            , Event "Cross of Gold Speech" 1896 "William Jenning Bryan's pro-farmer (and slightly pro-silver) speech made him the darling of the Populists, who named the Democrat as their candidate; they were essentially absorbed back into the Democratic party after."
            , Event "Minor v . Happersett" 1876 "Virginia Minor was found to be a citizen... but not to have the right to vote."
            , Event "\"The Yellow Wallpaper\"" 1892 "Charlotte Perkins Gilman's famous story...."
            , Event "Hull House founded" 1889 "One of many Settlement Houses that allowed middle-class women (and some men) a way to serve the poor by living in poor neighborhoods."
            , Event "The Gospel of Wealth" 1889 "Andrew Carnegie's famous essay."
            , Event "Chicago World's Fair/Columbian Exposition" 1893 "The \"White City\" celebrates progress."
            , Event "Atlanta Compromise Speech" 1895 "Booker T. Washington urges his Black and white audience to \"cast down your bucket where you are.\""
            , Event "United States v. Wong Kim Ark" 1898 "Supreme Court case that the birthright citizenship promised by the 14th amendment applies to the children of Chinese immigrants born in the US."
            , Event "Plessy v. Ferguson" 1896 "Infamous case establishing that \"separate but equal\" accommodations were consistent with the 14th amendment."
            , Event "Williams v. Mississippi" 1898 "Case established that rules to present African-Americans from voting were Constitutional if they were not explicitly about race."
            ]
          )
        , ( "X"
          , [Event "Neutrality Act of 1936" 1936 "Isolationism! Remember the Nye Commission that investigated whether Wall Street had really benefited from WWI..."
            , Event "American Liberty League founded" 1934 "Anti-New Deal group."
            , Event "Scopes Monkey Trial" 1925 "ACLU test case where Bert Scopes broke Tennessee's law against teaching evolution. Show trial with Clarence Darrow and William Jennings Bryan."
            , Event "\"The Klan's Defense of Americanism\"" 1926 "Hiram Walker Evan's defense of the plain folks, drivers of second hand Fords against the \"mongrelized\" Liberal."
            , Event "First Catholic candidate for President" 1928 "Al Smith!"
            , Event "Stock Market Crash" 1929 "The crash of the stock market."
            , Event "Depression Begins" 1931 "After a credit freeze, and bank runs (in the US and elsewhere) the country decends into depression"
            , Event "Glass-Steagall Act" 1933 "First New Deal banking reforms! Creates the FDIC!"
            , Event "Public Works Administration" 1933 "First New Deal jobs program! "
            , Event "Agricultural Adjustment Administration" 1933 "First New Deal program to raise farm prices!"
            , Event "Dust Bowl Begins" 1934 "Ecological distaster sending thousands of \"Okies\" to California (where they are blocked from entry)"
            , Event "National Recovery Act" 1933 "First New Deal program for businesses to voluntarily keep up wages, protect unions... and earn a Blue Eagle!"
            , Event "Tennessee Valley Authority" 1933 "First New Deal program to electrify Appalachia"
            , Event "End of Prohibition" 1933 "21st Amendment!"
            , Event "Election of Hitler" 1932 "Hitler elected"
            , Event "Berlin Olympics" 1936 "Olympics held in Berlin where Hitler snubbed Black athlete Jesse Owens."
            , Event "Social Security Act" 1935 "Second New Deal program to support people over 65 (note: life expectacy was 58 for men!)"
            , Event "Wagner Act" 1935 "Second New Deal pro-labor movement law, Labor's Magna Carta; creates the National Labor Relations Board"
            , Event "Schecter Case" 1935 "Ooops: the National Recovery was unconstitutional... maybe the rest of the New Deal was, too..."
            , Event "Court Packing" 1937 "FDR proposes adding justices to the Court; generally seen as a tyrannical act. (It doesn't happen.)"
            , Event "Conservative Manifesto" 1937 "Southern Democrat Josiah Bailey comes out against the New Deal"
            , Event "Works Progress Administration" 1935 "HUGE Second New Deal Works program, including Federal One, the arts program."
            , Event "West Coast Hotel v. Parrish" 1937 "After (but unrelated to) the court packing proposal, the Supreme Court decides the New Deal is okay"
            , Event "WWII begins" 1939 "Germany invades Poland. The US stays neutral"
            , Event "Four Freedoms Speech" 1941 "FDR speaks not only of the Freedom OF speech, but freedom FROM fear and want."
            ]
          )
        ]
        
