module EventList exposing (..)

import Dict
import Types exposing (Event)


unitDict : Dict.Dict String (List Event)
unitDict =
    Dict.fromList
        [ ( "I"
          , [ Event "Founding of Jamestown" 1607 "First permanent British settlement in what would become the United States. Built on tabacco and trade with Native Americans, it had many more men than women—and an extremely high death rate in the early years."
            , Event "First slaves in British America" 1619 "Slavery did not become popular in Virginia until around 1660 because of the high death rate of residents...."
            , Event "The Mayflower arrives in Plimouth" 1620 "The \"Pilgrims\" of Plimouth were a slightly different form of protestantism than the Puritans of the Massachusetts Bay Colony; the two colonies were merged at the end of the 17th century. Though the Mayflower Company was intended to make money to repay its investors, it wasn't until the colony gave up its communal cultivation of land that it stopped being in danger of starving. (They would of course have starved without help from their Native American neighbors.)"
            , Event "Boston founded" 1630 "Named after Boston, England, Boston was the capital of the Massachusetts Bay Colony"
            , Event "Charles the First executed" 1649 "Charles the First walked and talked half an hour after his head was cut off."
            , Event "Hobbes' Leviathan Published" 1651 "Hobbes' work justified monarchy in the human attempt to escape the \"nasty, brutish, solitary, and short\" State of Warre"
            , Event "Restoration of the Monarchy in Britain" 1660 "After the \"Commonwealth Period\" when the British decided they didn't like Puritan rule under Oliver Cromwell, Charles II was restored to the throne."
            , Event "First slave law in Virginia" 1661 "This was the first of a series of laws that had the effect of closing off avenues to freedom and separating Black slaves and white indentured servants."
            , Event "King Phillip's War begins" 1675 "The bloodiest war in US History in terms of the percentage of residents killed as a \"Pan-Indian\" alliance under the Wampanoag leader Metacom pushed back against English settler encroachment"
            , Event "Dominion of New England created" 1686 "As part of the restored English monarchy's attempt to raise funds, Massachusetts, New York, and other colonies are merged into a mega-colony under the hated Sir Edmond Andros. After James II is deposed, the colonies revert to their earlier charters."
            , Event "Glorious Revolution of 1688" 1688 "After the Catholic James II had a son (replacing James' Protestant daughter Mary in the succession), he was deposed."
            , Event "Second Treatise on Civil Goverment" 1689 "Locke's seminal work justifying the Glorious Revolution of 1688 spelled out the right to revolution against a tyrannical goverment and promoted the (common!) idea that a person owned what they had created by their labor... unless someone else was paying for that labor."
            , Event "Salem Witch Hysteria" 1692 "There is no concensus as to what happened to turn the people of village of Danvers (not Salem) against their neighbors—was it ergot? the anxiety of Massachusetts' losing its status as a Puritan theocracy with most British control in the new 1691 charter? A land grab? Punishment against outspoken women? Undisputed: 19 were hanged, and six others lost their lives."
            ]
          )
        , ( "II"
          , [ Event "Navigation Acts" 1660 "The Navigation Acts restricted colonial trade and imposed various taxes as part of James II's attempt to raise funds."
            , Event "\"The Grumbling Hive\"" 1705 "This scandalous poem by Bernard Mandeville explored the idea that greed is good for the economy"
            , Event "Fort Necessity" 1754 "A young George Washington makes several poor tactical and diplomatic decisions in the Ohio River valley and, Horace Walpole said, \"set the world on fire.\""
            , Event "The Albany Plan of Union" 1754 "Benjamin Franklin propsed the first intercontinental government to protect the colonies from France; his famous \"Join or Die\" cartoon supported the failed proposal."
            , Event "Seven Year's War begins" 1756 "Seven Year's War begins"
            , Event "Peace of Paris" 1763 "The treaty ended the Seven Year's War, giving India and Canada to the British"
            , Event "Proclamation Line" 1763 "To avoid more frontier wars after Pontiac's \"pan-Indian\" rebellion, the British restricted settlement past the Appalachians."
            , Event "Sugar Tax" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British lowered the old Molasses tax but pledged to enforce it, trying smugglers in courts of admiralty."
            , Event "Currency Act" 1764 "As part of the attempt to raise funds and lower costs to pay for the debt of the Seven Year's War, the British insisted all taxes from the colonies must be paid in gold or silver. Peter Cooper argued this was the cause of the Revolution."
            , Event "Stamp Act" 1765 "Though never enforced, this tax on paper and products made with paper caused widespread rioting across the colonies."
            , Event "Stamp Act Congress" 1765 "The Stamp Act Congress was the first successful intercolonial organization, bringing together nine of the colonies."
            , Event "Declaratory Act" 1766 "After repealing the Stamp Tax, Parliament asserted it still had the power to make legislation for the colonies."
            , Event "James Otis' speech against Writs of Assistance" 1761 "Otis' fiery speech against the warrantless searches illustrates the colonial belief that their freedoms came from the Magna Carta."
            , Event "Townshend Acts" 1767 "These taxes on middle class goods such as tea, paper, and glass spured the non-importation agreements and  Homespun Movement. Rioting in Boston brought troops to the city."
            , Event "Boston Massacre" 1770 "Paul Revere's engraving of the killing of five Bostonians by the British troops helped turn popular opinion against the British"
            , Event "Tea Act" 1773 "The Tea Act seems to fulfill the earlier warnings of John Dickinson that Parliament would \"complete\" the enslavement of the colonists by requiring them to import a good and then tax it."
            , Event "Tea Party" 1773 "In response to the Tea Act, an organized band in Boston destroyed the equivalent of four million dollars of tea."
            , Event "Intolerable Acts" 1774 "Called the \"Coercive Acts\" in Britain, these laws were in place until Massachusetts repaid what was destroyed in the Tea Party. The acts included closing Boston Harbor and dissolving the colonial government. The Québec Act was not part of the Coercive Acts, but it seemed part of the Catholic plot to enslave the colonists."
            , Event "Battle of Lexington and Concord" 1775 "On the 18th of April, in '75—hardly a man is now alive to remember that famous day and year.... Minutemen fanned across Middlesex county to warn the redcoats were planning to seize the colony's power and arrest the rebel leaders"
            , Event "Olive Branch Petition" 1775 "In the summer, the Continental Congress attempts to smooth things over with the King. (The Petition is ignored.)"
            , Event "Common Sense published" 1776 "Credited with addressing many loyalist concerns and using religious and Enlightenment imagry to rouse the population, Thomas Paine's tract was credited by many, including George Washington, with turning public opinion in favor of the Patriots."
            , Event "Wealth of Nations published" 1776 "Adam Smith's seminal work promoted the idea of an \"invisible hand in the market.\" Arguing that self-interest made an unregulated market self-regulation, Smith argued against older Mercantilist ideas."
            , Event "The Spirit of the Laws" 1748 "Montesquieu's book laid out the idea of checks and balances that would allow self-interest to prevent tyranny"
            , Event "The Declaration of Independence" 1776 "When in the Course of human events it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the Powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation."
            , Event "Treaty of Paris" 1783 "The Treaty of Paris ended the American Revolution, acknowledging that these United Colonies are, and of Right ought to be Free and Independent States... or at least, that they were now free and 13 separate entities."
            ]
          )
        ]



--  ("VI", [Event "Black Codes" 1865 "Mississippi and other states create laws to ensure continued labor supply and limit white/Black social contact."
--         , Event "Civil Rights Act 1866" 1866 "Much like the 14th amendment, the Civil Rights Act outlawed Black codes in the states. Vetoed by Johnson, then the veto overturned."
--         , Event "Reconstruction Act" 1867 "Divided the former Confederate states into five military districts until they accepted the 14th amendment."
--         , Event "14th Amendment " 1868 "Established equal protection under the law by race; birthright citizenship (and more)"
--         , Event "Founding of the KKK" 1865 "The Ku Klux Klan is founded in response to reconstruction to maintain strict former racial hirearchies of slavery"
--         , Event "15th Amendment" 1870 "The US expands the franchize to Black men"
--         , Event "Democratic Platform \"This is a white man's Government\"" 1868 "Democratic platform argues Republicans are aiming for \"Negro Suppremacy\""
--         , Event "Enforcement Acts" 1870 "Provide federal government authority for reconstruction"
--         , Event "Colfax Massacre" 1873 "One of the most violent race riots in the South, led by the KKK"
--         , Event "Slaughterhouse Cases" 1873 "placeholder"
--         , Event "Whiskey Ring" 1875 "placeholder"
--         , Event "Molly Maguires Strike" 1875 "placeholder"
--         , Event "Paris Commune" 1871 "placeholder"
--         , Event "Cruikshank" 1876 "placeholder"
--         , Event "Great Railroad Strike" 1877 "placeholder"
--         , Event "Bargain of 1877" 1877 "placeholder"
--         , Event "Panic of 1873" 1873 "placeholder"])
-- , ("VII", [Event "Haymarket" 1886 "placeholder"
--           , Event "Pullman Strike" 1894 "placeholder"
--           , Event "Homestead Strike" 1892 "placeholder"
--           , Event "Knights of Labor Founded" 1869 "placeholder"
--           , Event "AFL founded" 1886 "placeholder"
--           , Event "Munn v. IL" 1876 "placeholder"
--           , Event "Wabash" 1886 "placeholder"
--           , Event "Interstate Commerce Act" 1887 "placeholder"
--           , Event "Sherman Anti-Trust Act" 1890 "placeholder"
--           , Event "Populist Platform" 1892 "placeholder"
--           , Event "Cross of Gold Speech" 1896 "placeholder"
--           , Event "Minor v . Happersett" 1876 "placeholder"
--           , Event "\"The Yellow Wallpaper\"" 1892 "placeholder"
--           , Event "Hull House founded" 1889 "placeholder"
--           , Event "The Gospel of Wealth" 1889 "placeholder"
--           , Event "Hawaii becomes a territory" 1898 "placeholder"
--           , Event "Pledge of Allegiance written" 1892 "placeholder"
--           , Event "Spanish-American War" 1898 "placeholder"
--           , Event "Roosevelt Corollary" 1905 "placeholder"
--           , Event "\"The Significance of the Frontier on American Life\"" 1890 "placeholder"
--           , Event "Atlanta Compromise Speech" 1895 "placeholder"])
-- ,("VIII", [Event "Principals of Scientific Management" 1911 "placeholder"
--           , Event "Buck v. Bell" 1925 "placeholder"
--           , Event "Pure Food and Drug Act" 1906 "placeholder"
--           , Event "Hepburn Act" 1908 "placeholder"
--           , Event "Clayton Act" 1912 "placeholder"
--           , Event "Owens-Keating Act" 1916 "placeholder"
--           , Event "16th Amendment" 1913 "placeholder"
--           , Event "17th Amendment" 1913 "placeholder"
--           , Event "18th Amendment" 1918 "placeholder"
--           , Event "19th Amendment" 1920 "placeholder"
--           , Event "Sinking of Luisitania" 1915 "placeholder"
--           , Event "WWI breaks out" 1914 "placeholder"
--           , Event "Zimmerman Telegram" 1917 "placeholder"
--           , Event "US joins WWI" 1917 "placeholder"
--           , Event "WWI ends" 1918 "placeholder"
--           , Event "Espinoage Act" 1917 "placeholder"
--           , Event "Sedition Act" 1918 "placeholder"
--           , Event "Treaty of Versailles" 1919 "placeholder"
--           , Event "Johnson-Reed Act" 1924 "placeholder"
--           , Event "Birth of a Nation" 1915 "placeholder"
--           , Event "Founding of the NAACP" 1909 "placeholder"
--           , Event "Neutrality Act of 1936" 1936 "placeholder"])
-- , ("IX", [Event "Scopes Monkey Trial" 1925 "placeholder"
--          , Event "\"The Klan's Defense of Americanism\"" 1926 "placeholder"
--          , Event "First Catholic candidate for President" 1928 "placeholder"
--          , Event "Stock Market Crash" 1929 "placeholder"
--          , Event "Depression Begins" 1931 "placeholder"
--          , Event "Glass-Steagall Act" 1933 "placeholder"
--          , Event "Public Works Administration" 1933 "placeholder"
--          , Event "Agricultural Adjustment Administration" 1933 "placeholder"
--          , Event "Dust Bowl Begins" 1934 "placeholder"
--          , Event "National Recovery Act" 1933 "placeholder"
--          , Event "TVA" 1933 "placeholder"
--          , Event "End of Prohibition" 1933 "placeholder"
--          , Event "Election of Hitler" 1932 "placeholder"
--          , Event "Berlin Olympics" 1936 "placeholder"
--          , Event "Social Security Act" 1935 "placeholder"
--          , Event "Wagner Act" 1935 "placeholder"
--          , Event "Schecter Case" 1935 "placeholder"
--          , Event "Court Packing" 1937 "placeholder"
--          , Event "Conservative Manifesto" 1937 "placeholder"
--          , Event "WPA" 1935 "placeholder"
--          , Event "West Coast Hotel" 1937 "placeholder"
--          , Event "WWII begins" 1939 "placeholder"
--          , Event "Lend-Lease Act" 1941 "placeholder"
--          , Event "Cash and Carry Act" 1939 "placeholder"
--          , Event "Four Freedoms Speech" 1941 "placeholder"
--          , Event "Pearl Harbor" 1941 "placeholder"
--          , Event "Executive Order 8802" 1941 "placeholder"
--          , Event "Executive Order 9088" 1942 "placeholder"
--          , Event "Jackie Robinson!" 1947 "placeholder"
--          , Event "What the Negro Wants" 1944 "placeholder"
--          , Event "Race and Racism" 1942 "placeholder"
--          , Event "The Road to Serfdom" 1943 "placeholder"
--          , Event "The American Dilemma" 1944 "placeholder"
--          , Event "First black author of a book-of-the-month-club book" 1940 "placeholder"
--          , Event "Korematsu" 1944 "placeholder"
--          , Event "Desegregation of the Military" 1948 "placeholder"
--          , Event "Civil Rights Plank in Democratic Platform" 1948 "placeholder"
--          , Event "Dixiecrats" 1948 "placeholder"
--          , Event "Marshall Plan" 1948 "placeholder"
--          , Event "Truman Doctrine" 1947 "placeholder"
--          , Event "NATO founded" 1949 "placeholder"
--          , Event "UN Founded" 1945 "placeholder"
--          , Event "Bretton Woods" 1945 "placeholder"
--          , Event "World Bank Founded" 1945 "placeholder"
--          , Event "IMF Founded" 1945 "placeholder"
--          , Event "First Atomic Bomb" 1945 "placeholder"
--          , Event "First Hydrogen Bomb" 1954 "placeholder"
--          , Event "Russia gets the Bomb" 1949 "placeholder"
--          , Event "Mao Chairman of China" 1949 "placeholder"
--          , Event "Korean War Begins" 1950 "placeholder"
--          , Event "Truman puts the Bomb under Civilian Control" 1946 "placeholder"
--          , Event "McCarran Internal Security Act" 1950 "placeholder"
--          , Event "First Levittown" 1947 "placeholder"
--          , Event "Eisenhower Defensive Highway Act" 1956 "placeholder"
--          , Event "Eisenhower warns of the \"Military Industrial Complex\"" 1960 "placeholder"
--          , Event "US helps coup in Guatemala" 1954 "placeholder"
--          , Event "US helps install Shah in Iran" 1955 "placeholder"
--          , Event "Sputnik" 1957 "placeholder"
--          , Event "Cuban Revolution" 1959 "placeholder"])
-- ,("X", [Event "Brown v. Board" 1954 "placeholder"
--        , Event "Emmett Till" 1955 "placeholder"
--        , Event "Montgomery Bus Boycott" 1955 "placeholder"
--        , Event "Greensboro Sit-ins" 1960 "placeholder"
--        , Event "SNCC founded" 1960 "placeholder"
--        , Event "March on Washington" 1963 "placeholder"
--        , Event "Nation of Islam founded" 1930 "placeholder"
--        , Event "\"Children's Crusade\"" 1963 "placeholder"
--        , Event "Kennedy Assassinated" 1963 "placeholder"
--        , Event "Civil Rights Act of 1964" 1964 "placeholder"
--        , Event "Voting Rights Act" 1965 "placeholder"
--        , Event "Fair Housing Act" 1968 "placeholder"
--        , Event "Watts Riots" 1965 "placeholder"
--        , Event "Kerner Commission" 1967 "placeholder"
--        , Event "Moynihan Report" 1965 "placeholder"
--        , Event "Black Panther Party founded" 1966 "placeholder"
--        , Event "Malcolm X assassinated" 1965 "placeholder"
--        , Event "King assassinated" 1968 "placeholder"
--        , Event "Bay of Pigs" 1961 "placeholder"
--        , Event "Cuban Missile Crisis" 1962 "placeholder"
--        , Event "Gulf of Tonkin Resolution" 1964 "placeholder"
--        , Event "Tet Offensive" 1968 "placeholder"
--        , Event "My Lai Massacre" 1969 "placeholder"
--        , Event "Pentagon Papers" 1971 "placeholder"
--        , Event "Watergate" 1973 "placeholder"
--        , Event "Kent State" 1970 "placeholder"
--        , Event "Pigasus runs for president" 1968 "placeholder"
--        , Event "Oil Embargo" 1973 "placeholder"
--        , Event "Nixon goes off the gold standard" 1971 "placeholder"
--        , Event "EPA founded" 1970 "placeholder"
--        , Event "\"Malaise\" Speech" 1979 "placeholder"
--        , Event "Nixon resigns" 1974 "placeholder"
--        , Event "Vietnam War ends" 1975 "placeholder"
--        , Event "Iranian Revolution" 1979 "placeholder"
--        , Event "Three-Mile Island" 1979 "placeholder"
--        , Event "Roe" 1973 "placeholder"
--        , Event "Griswold v. CT" 1965 "placeholder"
--        , Event "Miranda" 1966 "placeholder"
--        , Event "Gideon" 1963 "placeholder"
--        , Event "Loving v. Virginia" 1967 "placeholder"])]
